---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-registry
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-registry
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["aws-registry-credentials"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-registry
subjects:
  - kind: ServiceAccount
    name: aws-registry
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-registry
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-registry
    template:
      metadata:
        labels:
          app.kubernetes.io/name: aws-registry
      spec:
        serviceAccountName: aws-registry
        securityContext:
        containers:
          - name: aws
            image: aws-registry:latest
            args: ["awsregistry", "--in-cluster"]
            securityContext:
              runAsUser: 0
              runAsGroup: 0
            envFrom:
              secretRef:
                name: awsregistry-config
            volumeMounts:
              - name: aws
                mountPath: /root/.aws
                mountPropagation: HostToContainer
                readOnly: true 
        volumes:
          - name: aws
            hostPath: /home/ubuntu/aws
              
